# include mydefault.css
include orange_warm.css

font_family GeistMono Nerd Font Mono
font_size 10

disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 8
cursor_blink_interval 0

background_opacity 0.70
scrollbar_handle_opacity        0
scrollbar_track_opacity         0
scrollbar_track_hover_opacity   0
confirm_os_window_close         0

sync_to_monitor no

# Tab Bar

active_tab_foreground   #282c34
active_tab_background   #979eab
inactive_tab_foreground #abb2bf
inactive_tab_background #282c34


