separator=" "
colon=" "

print_info() {
    local red="\033[38;2;255;0;0m"
    local white="\033[38;2;255;255;255m"
    local pink="\033[38;2;255;0;127m"
    local coral="\033[38;2;255;79;80m"
    local orange="\033[38;2;255;140;0m"
    local amber="\033[38;2;255;191;0m"
    local yellow="\033[38;2;255;255;0m"
    local lemon="\033[38;2;255;250;205m"
    local reset="\033[0m"
    
    #empty lines[\n]
     prin "" 
     prin "" 
    # prin ""
    # prin ""
    # prin ""
    # prin ""
    # prin ""
    # prin ""
    # prin ""

    prin "${red}${USER}${white}@${red}${HOSTNAME}${reset}"
    prin "${red}--------------${reset}"
    
    info "${pink}󰣇 ${red}OS ${white}❯${reset}" distro
    info "${coral}󰌽 ${red}Kernel ${white}❯${reset}" kernel
    info "${orange}󰏖 ${red}Uptime ${white}❯${reset}" uptime
    info "${amber}󱆃 ${red}Shell ${white}❯${reset}" shell
    local wm = "Hyprland"
    get_wm() {
        wm="Hyprland"
    }
    info "${yellow} ${red}WM ${white}❯${reset}" wm
    info "${lemon}󰆍 ${red}Terminal ${white}❯${reset}" term

    prin "" 
    prin "$(color 1)● $(color 2)● $(color 3)● $(color 4)● $(color 5)● $(color 6)● $(color 7)● $(color 8)●${reset}"
}
image_backend="ascii"
image_source="${HOME}/.config/neofetch/ASCII_art/2.txt"
# --- Ascii Options ---
ascii_bold="off"

# This stops neofetch from trying to be "smart" about the image
crop_mode="none"
crop_offset="center"
