#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#exec-once = $terminal
#exec-once = nm-applet &
#exec-once = waybar & hyprpaper & firefox
exec-once = waybar > /dev/null 2>&1
exec-once = swaync > /dev/null 2>&1
exec-once = swww-daemon > /dev/null 2>&1

